spring:
  datasource:    url: jdbc:mariadb://reserv.c2xpobnsaert.ap-northeast-2.rds.amazonaws.com/reserv?autoReconnect=true&useSSL=false&serverTimezone=UTC
    driverClassName: org.mariadb.jdbc.Driver
    username: reserv
    password: '!1qazsoftj'
mybatis:  type-aliases-package: com.example.cheongsihaengbeach.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
server:
  port: 80